// import Head from "next/head";

// import styles from "../styles/Home.module.scss";
// export default function AboutPage() {
//   return (
//     <>
//       <div className={styles.container}>
//         <Head>
//           <title>About - Sifat Bhatia</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>

//         <main>
//           <section className={styles.hero}>
//             <h1 className={styles.h1}> </h1>
//             <h1 className={styles.h1}>About</h1>
//           </section>
//         </main>
//       </div>
//     </>
//   );
// }

import React from "react";
import Lottie from "react-lottie";
import animationData from "./94146-coming-soon.json";
export default function About() {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    background:"#000000" ,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  return (
      <>
          <Lottie options={defaultOptions}  />
</>
  )
}

